name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build-type: [debug, release]
        include:
        - build-type: release
          build-flag: "--release"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libudev-dev
    - name: Install cargo-deny
      if: ${{ matrix.build-type == 'debug' }}
      run: cargo install --locked cargo-deny
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target
        key: cargo-${{ runner.os }}-${{ matrix.build-type }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose ${{ matrix.build-flag }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.build-flag }}
    - name: Check format
      if: ${{ matrix.build-type == 'debug' }}
      run: cargo fmt --all --check
    - name: Clippy
      run: cargo clippy --no-deps ${{ matrix.build-flag }} -- -Dwarnings
    - name: Check licenses
      if: ${{ matrix.build-type == 'debug' }}
      run: cargo deny check licenses
